/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,ts}"],
  theme: {
    colors: {
      transparent: "transparent",
      current: "currentColor",
      "neutral-white": "#FFFFFF",
      "neutral-lightest": "#F4F4F5",
      "neutral-light": "#D3D4D8",
      "neutral-dark": "#91929D",
      "neutral-darkest": "#4F5162",
      "neutral-black": "#23263B",
      "xenon-base": "#003DFF",
      "black-base": "#23263B",
      "success-dark": "#06AF87",
      "success-light": "#B9FFEE",
      "informative-dark": "#1363C1",
      "informative-light": "#D1E5FD",
      "warning-dark": "#E07E0B",
      "warning-light": "#FFE2BF",
      "error-dark": "#D9293E",
      "error-light": "#FFD4DA",
      "primary-dark": "#23263B",
      "primary-light": "#FFFFFF",
      "secondary-dark": "#91929D",
      "secondary-light": "#F4F4F5",
      link: "#003DFF",
    },
    extend: {},
  },
  plugins: [],
};
